version: '3'
services:
  memcached:
    image: memcached:1.4
    container_name: memcached
    networks:
        - eosio_api_network
    restart: on-failure
  get_accounts:
    build: ./services/get_accounts
    environment:
        - GET_ACCOUNTS_WORKERS=4
        - GET_ACCOUNTS_UPSTREAM_WORKERS=4
        - GET_ACCOUNTS_LIMIT=20
        - UPSTREAM_API=https://api.eostribe.io
    networks:
        - eosio_api_network
    ports:
        - "8905:8000"
    restart: on-failure
    volumes:
        - .:/src
  get_actions:
    build: ./services/get_actions
    environment:
        - GET_ACTIONS_WORKERS=4
    networks:
        - eosio_api_network
    ports:
        - "8902:8000"
    restart: on-failure
    volumes:
        - .:/src
  get_blocks:
    build: ./services/get_blocks
    environment:
       - GET_BLOCKS_WORKERS=4
       - GET_BLOCKS_UPSTREAM_WORKERS=4
       - GET_BLOCKS_LIMIT=20
       - UPSTREAM_API=https://api.eostribe.io
    networks:
        - eosio_api_network
    ports:
        - "8903:8000"
    restart: on-failure
    volumes:
        - .:/src
  get_currency_balances:
    build: ./services/get_currency_balances
    environment:
        - CACHE_EXPIRATION_TIME=600
        - GET_CURRENCY_BALANCES_WORKERS=40
        - GET_UPSTREAM_BALANCES_WORKERS=100
        - UPSTREAM_API=https://api.eostribe.io
    networks:
        - eosio_api_network
    ports:
        - "8901:8000"
    links:
        - memcached
    restart: on-failure
    volumes:
        - .:/src
networks:
    eosio_api_network:
        external: true
